- name: Copy mysql config
  template:
    src=templates/my.cnf.j2
    dest=/etc/my.cnf
    backup=yes
    mode=755

- name: Restart Mysql Service
  service: name=mysqld state=restarted enabled=true

- name: Create /opt/mysql-replication directory
  file:
    path=/opt/mysql-replication
    group={{bahmni_group}}
    owner={{bahmni_user}}
    mode=0755
    state=directory
    recurse=yes

- name: stop replication
  mysql_replication:
   mode: stopslave
   login_user: "{{ mysql_root_user}}"
   login_password: "{{ mysql_root_password }}"
  ignore_errors: true


- name: Replication setup in master
  include: master.yml
  when: inventory_hostname in groups['bahmni-emr-db']
  tags: master

- name: Replication setup in slave
  include: slave.yml
  when: inventory_hostname in groups['bahmni-emr-db-slave']
  tags: slave

- name: Replication setup in master
  include: master.yml
  when: inventory_hostname in groups['bahmni-reports-db']
  tags: master

- name: Replication setup in slave
  include: slave.yml
  when: inventory_hostname in groups['bahmni-reports-db-slave']
  tags: slave