openmrs_port: 8081
openmrs_modules_dir: /home/bahmni/.OpenMRS/modules
openmrs_context_path: openmrs
openmrs_server_args: "-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m"
openmrs_debug_args: "-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"

openmrs_auto_update_database: "true"
openmrs_db_username: openmrs-user
openmrs_db_password: password
openmrs_application_data_directory: /opt/openmrs/
openmrs_module_allow_web_admin: "false"
openmrs_install_dir: /opt/openmrs

mysql_root_user: root
mysql_root_password: password
openmrs_user_id: admin
openmrs_user_password : test

bahmni_group: bahmni
bahmni_user: bahmni
omods: []

openelis_port: 8081

