download_folder: /opt

postgres_repo_rpm_name: pgdg-centos92-9.2-7.noarch.rpm
postgres_repo_download_url: http://yum.postgresql.org/9.2/redhat/rhel-6-x86_64/{{postgres_repo_rpm_name}}
postgres_repo_rpm_location: "{{download_folder}}/{{ postgres_repo_rpm_name}}"

openerp_db_username: openerp
openerp_db_password: openerp

mx_download_url: ftp://195.220.108.108/linux/Mandriva/devel/cooker/x86_64/media/contrib/release/mx-1.4.5-1-mdv2012.0.x86_64.rpm
