
- name: copy ssl conf file
  template:
      src=ssl.conf.j2
      dest=/etc/httpd/conf.d/ssl.conf
      mode=644
      owner={{ bahmni_user }}
      group={{ bahmni_group }}

- name: Switch off chkconfig for httpd on passive
  service: name=httpd state=stopped enabled=no
  when: passive is defined and passive == 'yes'

- name: Stop httpd
  service: name=httpd state=stopped
  tags: 
      - run_bahmni_web
      - stop_bahmni
  when: passive is not defined or passive != 'yes'

- name: Start httpd
  service: name=httpd state=started enabled=yes
  tags:
      - run_bahmni_web
      - start_bahmni
  when: passive is not defined or passive != 'yes'


