- name: Create bahmni_support group
  group:
    name={{ bahmni_support_group }}
    state=present


- name: Create bahmni_support user
  user:
   name={{ bahmni_support_user }}
   group={{ bahmni_support_group }}
   generate_ssh_key=yes
   ssh_key_bits=2048
   password={{bahmni_password_hash}}
   state=present


- name: configure sudoers
  lineinfile: "dest=/etc/sudoers state=present backup=yes regexp='^{{bahmni_support_user}}' insertafter='^# %wheel' line='{{bahmni_support_user}} ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  ignore_errors: true


- name: allow bahmni_support_group ssh access
  lineinfile:
    dest=/etc/ssh/sshd_config
    backrefs=yes
    backup=yes
    regexp='(AllowGroups(?!.*\b{{ bahmni_support_group }}\b).*)'
    state=present
    line='\1 {{ bahmni_support_group }}'
  tags:
    - sshd

- name: allow bahmni_support_user ssh access
  lineinfile:
    dest=/etc/ssh/sshd_config
    backrefs=yes
    backup=yes
    regexp='(AllowUsers(?!.*\b{{ bahmni_support_user }}\b).*)'
    state=present
    line='\1 {{ bahmni_support_user }}'
  tags:
    - sshd

- name: reload sshd
  service: name=sshd state=reloaded