download_folder: /opt
java_runtime: jre
java_version: 8u101
java_build: b13
java_rpm_name: "{{ java_runtime }}-{{ java_version }}-linux-x64.rpm"
java_download_url: "http://download.oracle.com/otn-pub/java/jdk/{{java_version}}-{{java_build}}/{{ java_rpm_name }}"
java_rpm_location: "{{download_folder}}/{{ java_rpm_name}}"
java_home_location: "/usr/java/{{java_runtime}}1.{{java_version | replace('u', '.0_')}}"
